### ISSUE TITLE
RX.TextInput default value always returns error/warning

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#289]
When trying to set a default value on page load, I always get this error:
![screen shot 2017-09-25 at 6 00 21 pm](https://user-images.githubusercontent.com/1202909/30833087-8ebf60fa-a21b-11e7-88b3-cf946deb0b17.png)

This is the simplest example that produces the error:
```jsx
import React from 'react'
import RX from 'reactxp'

export default class TextInputValue extends RX.Component {
  constructor(props) {
    super(props);

    this.state = {
        inputValue: 'hello'
    };
  }

  onChangeTextValue = (value) => {
    this.setState({ inputValue: value });
  }

  render() {
    return (
      <RX.TextInput
        placeholder="Placeholder"
        value={ this.state.inputValue }
        onChangeText={this.onChangeTextValue}
        // defaultValue={ this.state.inputValue }
        />
    );
  }
}
```
I tested as is (with `value`) alone and also tested with `defaultValue` alone, but no matter what, I keep getting that error. I would rather not use the `defaultValue`  and instead have the `value` prop pull in the default text from state. That way I can reuse the same field for inputting text as well as editing it, with the `value` being assigned its state from `inputValue`.

Any idea how to fix this to get rid of the pesky error?

**Comment by deregtd** [comment]
What version of react are you using?

**Comment by erictraut** [comment]
I suspect that the RN.TextInput's interface changed in a breaking way. We'll need to update RX's TextInput implementation accordingly. Which version of React Native are you using?

**Comment by erictraut** [comment]
Hmm, interesting. The RX implementation is providing an onChangeText handler but not an onChange handler. The documentation doesn't make any distinction between the two other than that onChangeText is passed the updated text. I suspect that the warning is a recently-introduced bug in RN. Once I know which version you're using, I'll investigate further.

**Comment by MovingGifts** [comment]
Thanks for the response guys, here is the relevant info:
```
"react": "^16.0.0-rc.3",
"react-dom": "^16.0.0-rc.3",
"react-native": "0.46.0"
```

**Comment by MovingGifts** [comment]
I think this issue also occurred with the previous 0.42.0 version of react native as well.
Any update on the fix eta?

**Comment by MovingGifts** [comment]
@erictraut Any update on the investigation of the error and a possible solution?

**Comment by MovingGifts** [comment]
@deregtd  @erictraut Hey, sorry to write again but was this ever resolved? How can one supply a default value but without this error in ReactXP?

**Comment by erictraut** [comment]
I haven't had time to look into it yet. Busy with other things. Feel free to investigate and propose a fix.

**Comment by MovingGifts** [comment]
Is there any way to prevent this error from showing in console? I tried to set the app like this to hide errors but it doesn't seem to hide them:

```RX.App.initialize(false, false);```

Following this signature:

```initialize(debug: false, development: false);```

Shouldn't errors not show in console if debug and development modes are both false?

**Comment by degroote22** [comment]
On the React side of things, [since 2015 they've decided that onChange supersedes onInput.](https://github.com/facebook/react/issues/3964)

[They're not going to change it.](https://github.com/facebook/react/pull/8550#issuecomment-266248335)

[And people agree that changing it would be bad.](https://stackoverflow.com/questions/38256332/in-react-whats-the-difference-between-onchange-and-oninput)
> I agree 100% with the comment... But I guess changing it now would bring more problems than it solves since so much code had already been written that relies on this behavior (and it has also been copied to other frameworks, e.g. Preact).

I guess that ReactXP should use onChange on [these](https://github.com/Microsoft/reactxp/blob/master/src/web/TextInput.tsx#L116) [lines](https://github.com/Microsoft/reactxp/blob/master/src/web/TextInput.tsx#L91) and the problem would be gone.
Are there any other reasons not to do this?
If the maintainers are happy with this approach I'd be happy to submit a PR.

**Comment by MovingGifts** [comment]
@degroote22 It would be nice to get rid of this error, as it is always in console. If you tried your approach and it works perfectly, you can submit a PR but maybe check with @erictraut first, since he merges PRs he's happy with 👍

**Comment by erictraut** [comment]
I fixed the underlying cause of the error. I also conditionalized all of the console output in ReactXP based on the development flag specified in the RX.App.Initialize call.

**Comment by MovingGifts** [comment]
Thank you for fixing both! I look forward to those errors going away now :)

Which reactxp version will it be in btw?

**Comment by erictraut** [comment]
This is in 0.51.0-alpha.1 and newer.

**Comment by MovingGifts** [comment]
@erictraut I have `"reactxp": "^0.51.2"` in my `package.json` installed, but it seems the issue is still there as I still get this in console:

```warning.js:33 Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `TextInput`.```

Any idea why the fix isn't applied to this version?

**Comment by erictraut** [comment]
Which version of react and react-dom are yo using? The current ReactXP implementation of TextInput uses an onInput handler rather than onChange. React used to allow either of these. I suspect that in a recent version of react, they've decided to require onChange rather than onInput. 

Does it work as expected? If so, you can ignore the warning for now, and we'll address it in a future version of ReactXP.

**Comment by MovingGifts** [comment]
I'm using these versions:
```
"react": "^15.6.2",
"react-dom": "^15.6.2",
"reactxp": "^0.51.2"
```
That error shows in console, but functionality works as expected. Just wanted to report it once again as it was still present after your solution was implemented.

**Comment by andraz** [comment]
Can confirm, I get the same problem after adding TextInput to hello-world-js example:
```
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-native": "^0.51.0",
    "react-native-windows": "^0.51.0-rc.1",
    "reactxp": "^0.51.0",
    "reactxp-imagesvg": "^0.2.8",
    "reactxp-navigation": "^1.0.15",
    "reactxp-video": "^0.2.3"
```

**Comment by erictraut** [comment]
The fix will be in reactxp 1.0.2.

**Comment by erictraut** [comment]
The latest version of reactxp is 1.3.0.

**Comment by MovingGifts** [comment]
Hmmm... So when I did:

`npm i -S reactxp`

It gave me `"reactxp": "^0.51.10”`

I thought by default I would get the latest version of the package.

Instead, to get the latest version of the package I had to do this:

`npm i -S reactxp@latest`

How come `npm i -S reactxp` is anchored at that version?
Apologies if I am missing something obvious.

**Comment by erictraut** [comment]
Npm honors the desired major and minor version. The “^” means that it should pick the highest build number (the third number in the version). Change your package.json to ask for ^1.3.0.

**Comment by MovingGifts** [comment]
Ah, that makes sense. I really didn't know why it was happening! Thank you for pointing that out :)
